import { Footer, Navigation } from '@/components/globals'
import { ToastProvider } from '@/components/ui'
import { getSession } from '@/lib/auth/session'
import type { Metadata } from 'next'
import { SessionProvider } from 'next-auth/react'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import { Toaster } from 'sonner'
import './globals.css'

const inter = Inter({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter'
})

const dharmaGothic = localFont({
	src: './fonts/DharmaGothic.woff2',
	variable: '--font-dharma-gothic',
	weight: '400'
})

const clashGrotesk = localFont({
	src: './fonts/ClashGrotesk.woff2',
	variable: '--font-clash-grotesk',
	weight: '400'
})

const plusJakarta = localFont({
	src: './fonts/PlusJakarta.woff2',
	variable: '--font-plus-jakarta',
	weight: '400'
})
export const metadata: Metadata = {
	title: 'CONTPAQi profit',
	description: 'Generated by'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await getSession()

	return (
		<html lang="en">
			<body
				className={`${clashGrotesk.variable} ${plusJakarta.variable} ${dharmaGothic.variable} ${inter.variable} grid min-h-[100dvh] grid-rows-[auto_1fr_auto] font-inter antialiased`}
			>
				<ToastProvider>
					<SessionProvider>
						<Navigation session={session} />
						{children}
						<Footer />
						<Toaster />
					</SessionProvider>
				</ToastProvider>
			</body>
		</html>
	)
}
